const environment = "staging";
const app = document.querySelector("#app");
const apiBase = "/automation/staging";
const state = { capabilities: null, result: null, error: "", busy: false };
const escapeHtml = (value) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
async function loadCapabilities() { const response = await fetch(`${apiBase}/v1/capabilities`, { cache: "no-store" }); if (!response.ok) throw new Error(`Capabilities request failed (${response.status})`); state.capabilities = await response.json(); }
function render() { const capabilities = state.capabilities || { rerun: true, reset: true }; app.innerHTML = `<section class="shell"><header><p class="eyebrow">AUTOMATION / STAGING</p><h1>Automation Staging</h1><p>Route results are recorded locally. Zendesk delivery is disabled.</p></header><form id="case-form" class="panel"><label>Case ID<input name="case_id" required placeholder="AC-STAGING-001"></label><label>Subject<input name="subject" placeholder="Case subject"></label><label>Question<textarea name="question" required rows="6" placeholder="Customer request"></textarea></label><button type="submit" ${state.busy ? "disabled" : ""}>${state.busy ? "Preparing..." : "Run Route"}</button></form>${state.error ? `<p class="error">${escapeHtml(state.error)}</p>` : ""}${state.result ? `<pre class="result">${escapeHtml(JSON.stringify(state.result, null, 2))}</pre>` : ""}<footer>Capabilities: rerun=${Boolean(capabilities.rerun)} reset=${Boolean(capabilities.reset)}</footer></section>`; app.querySelector("#case-form")?.addEventListener("submit", submitCase); }
async function submitCase(event) { event.preventDefault(); state.busy = true; state.error = ""; render(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const response = await fetch(`${apiBase}/v1/cases`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, request_id: crypto.randomUUID() }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || `Request failed (${response.status})`); state.result = payload; } catch (error) { state.error = error instanceof Error ? error.message : "Request failed"; } state.busy = false; render(); }
loadCapabilities().catch((error) => { state.error = error instanceof Error ? error.message : "Capabilities unavailable"; }).finally(render);
