const environment = "production";
const app = document.querySelector("#app");
const apiBase = "/automation/production";
const state = { capabilities: null, result: null, error: "", busy: false };
const escapeHtml = (value) => String(value ?? "").replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;").replaceAll('"', "&quot;");
async function loadCapabilities() { const response = await fetch(`${apiBase}/v1/capabilities`, { cache: "no-store" }); if (!response.ok) throw new Error(`Capabilities request failed (${response.status})`); state.capabilities = await response.json(); }
function render() { app.innerHTML = `<section class="shell"><header><p class="eyebrow">AUTOMATION / PRODUCTION</p><h1>Automation Production</h1><p>Production executes ownership, status and the explicitly selected Zendesk comment visibility.</p></header><form id="case-form" class="panel"><label>Case ID<input name="case_id" required placeholder="AC-PRODUCTION-001"></label><label>Zendesk ticket ID<input name="zendesk_ticket_id" required placeholder="123456"></label><label>Comment visibility<select name="comment_visibility" required><option value="">Select visibility</option><option value="internal">Internal comment</option><option value="external">External comment</option></select></label><label>Subject<input name="subject" placeholder="Case subject"></label><label>Question<textarea name="question" required rows="6" placeholder="Customer request"></textarea></label><button type="submit" ${state.busy ? "disabled" : ""}>${state.busy ? "Preparing..." : "Run Production"}</button></form>${state.error ? `<p class="error">${escapeHtml(state.error)}</p>` : ""}${state.result ? `<pre class="result">${escapeHtml(JSON.stringify(state.result, null, 2))}</pre>` : ""}<footer>Production requires an explicit comment visibility for every execution.</footer></section>`; app.querySelector("#case-form")?.addEventListener("submit", submitCase); }
async function submitCase(event) { event.preventDefault(); state.busy = true; state.error = ""; render(); const data = Object.fromEntries(new FormData(event.currentTarget)); try { const response = await fetch(`${apiBase}/v1/cases`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...data, request_id: crypto.randomUUID() }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.detail || `Request failed (${response.status})`); state.result = payload; } catch (error) { state.error = error instanceof Error ? error.message : "Request failed"; } state.busy = false; render(); }
loadCapabilities().catch((error) => { state.error = error instanceof Error ? error.message : "Capabilities unavailable"; }).finally(render);
